version: "3.3"

services:
  app:
    build: .
    image: payment-orchestration-demo
    container_name: payment-orchestration-demo
    ports:
      - "5000:5000"
    networks:
      - payment-orchestration-demo
    env_file:
     - ./.env

networks:
  payment-orchestration-demo:
    name: payment-orchestration-demo
